import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { ThemeProvider } from "next-themes";
import FloatingDock from "@/components/FloatingDock";
import { Providers } from "@/app/providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white dark:bg-black ${inter.className}`}>
      <ThemeProvider attribute="class">
      <Providers>
      <Navbar/>
        {children}
        <FloatingDock/>
        </Providers>
        </ThemeProvider>
        </body>
    </html>
  );
}
